name: 00 - Main CI / CD Pipeline

on:
  push:
    branches: ["main"]
    paths-ignore:
      - '**/*.md'
      - '**/*.txt'
  workflow_dispatch:

jobs:
  build:
    name: Build
    uses: ./.github/workflows/build.yml
    secrets: inherit

  sca:
    needs: build
    name: SCA
    uses: ./.github/workflows/sca.yml
    permissions:
      contents: read
      security-events: write
    secrets: inherit

  license-compliance:
    needs: build
    name: License Compliance
    uses: ./.github/workflows/license-compliance.yml
    permissions:
      contents: read
      security-events: write
    secrets: inherit

  sast:
    needs: build 
    name: SAST 
    uses: ./.github/workflows/sast.yml
    permissions:
      contents: read
      security-events: write
    secrets: inherit

  docker:
    needs: [build, sca, license-compliance, sast]
    name: Docker Build & Push
    uses: ./.github/workflows/docker.yml
    permissions:
      contents: read
      packages: write
    secrets: inherit

  container-image-scan:
    needs: docker
    name: Container Image Scan
    uses: ./.github/workflows/container-image-scan.yml
    permissions:
      contents: read
      packages: read
      security-events: write
    secrets: inherit
    with:
      image-name: ${{ needs.docker.outputs.image-name }}
      image-tag: ${{ needs.docker.outputs.image-tag }}
